[package]
name = "hteaml-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = "2.0.61"
proc-macro2 = "1.0.82"

[lib]
proc-macro = true

[dev-dependencies]
hteaml = { path = "../hteaml" }

[lints]
workspace = true
